---
- hosts: centos
  tasks:

  - name: show hostname
    command: 'id'
    register: result
  - debug: msg="My hostname is {{ result.stdout }}" 

  - name: cat shadows
    command: 'cat /etc/shadow'
    register: result
  - debug: msg="My directory shadow is {{ result.stdout }}" 


  
