---
- hosts: centos
  tasks:

  - name: show id
    command: 'id'
    register: result
  - debug: msg="My Id is {{ result.stdout }}" 
  - name: show hostname
    shell: 'df -h'
    register: out
  - debug: var=out.stdout_lines
  - name: cat user
    command: 'cat /etc/shadows'
    register: show 
  - debug: var=show.stdout_lines


