---
- hosts: centos
  tasks:

  - name: show id
    command: 'id'
    register: result
  - debug: msg="My Id is {{ result.stdout }}" 
  - name: show hostname
    shell: 'df -h'
    register: out
  - debug: msg="My SIZE is {{ out.stdout_lines }}" 


