---
- hosts: centos
  tasks:

  - name: show hostname
    command: 'id'
    register: result
  - debug: msg="My ID is {{ result.stdout }}" 
  - name: Install Pip 
      easy_install:
        name: pip
        state: latest
      tags:
       - pip
  
