---
- hosts: centos
  tasks:


  - name: show Mod
    shell: cat /etc/motd
    register: pass_content
  - name: echo 
    shell: echo "pass_content the word"
    when: pass_content.stdout.find('hi') != -1
