---
- hosts: centos
  tasks:

  - name: show id
    command: 'id'
    register: result
  - debug: msg="My Id is {{ result.stdout }}" 
  - name: show hostname
    command: 'hostname'
    register: result
  - debug: msg="My hostname is {{ result.stdout }}" 
  - name: show  passwd
    shell: /usr/bin/uptime
    register: result
    
