---
- hosts: centos
  become_method: sudo
  become: true
  
  tasks:

  - name: show id
    command: 'id'
    register: result
  - debug: msg="My Id is {{ result.stdout }}" 
  - name: show hostname
    shell: 'df -h'
    register: out
  - debug: var=out.stdout_lines



